<?php

/**
 * Implementa hook_block_info().
 */
function pendingQuizs_block_info() {
  $blocks["pendingQuizs"] = array(
    "info" => "Quizs No respondidos por el usuario",
  );
  return $blocks;
}

/**
 * Implementa hook_block_view().
 */
function pendingQuizs_block_view($delta = "") {
  $block=array();
  switch ($delta) {
    case "pendingQuizs":
      $block["content"] = pending();
      return $block;   
  }
}

function pending()
{
  global $user;
  $user_data=$user->data['hybridauth'];
  $html='<div class="col-md-6 col-md-offset-2">
          <div style="clear: both; margin-top: 10px;"></div>';
          print_r($user_data['identifier'],true);
          $sql="SELECT * FROM quiz WHERE publicado=1 and id not in (select id_quiz from tweet where user_id ='".$user_data['identifier']."')";
          error_log($sql);
          $result=db_query($sql);
          if(!$result)
          {
            $html.="NO TIENES QUIZS PENDIENTES";
          }
          foreach ($result as $key) {

            $sqlHashtags="SELECT * FROM tweet WHERE id_quiz=".$key->id;
            $resultHashtags=db_query($sqlHashtags);
            $datos=array();
            foreach ($resultHashtags as $row) {
              $sqlDatos="SELECT answer,count(*) cuenta FROM tweet WHERE id_quiz =".$key->id." group by answer";
              $resultDatos=db_query($sqlDatos);
              foreach ($resultDatos as $dato) {
                $respuesta=$dato->cuenta;
                $datos[$dato->answer]=$respuesta;
              }
            }
            if(!isset($datos[A])){$datos[A]=0;}
            if(!isset($datos[B])){$datos[B]=0;}
            if(!isset($datos[C])){$datos[C]=0;}
            if(!isset($datos[D])){$datos[D]=0;}
            $html.='<div class="panel panel-primary"> 
              <div class="panel-heading">'.$key->name.': '.$key->title.'</div>
                <div class="panel-body">
                  <table class="borderless">
                    <tr style="width=100%">
                      <td style="float:left"><img class="left-block" src="sandra/images/'.$key->name.'.jpg"></td>
                      <td>
                        <a  href="https://twitter.com/medquizzes" style="margin-left:50%;  margin-top:4%;" target="blank">Responder</a>
                        <a  href="https://twitter.com/medquizzes" target="blank">
                          <img class="left-block goTwitter" style=" " src="sites/all/themes/medQuizs/assets/images/logoBlanco.png" alt="Ir a Twitter" />
                        </a>
                      </td>
                      <td style="float:right">
                        <canvas id="'.$key->name.'" class="results"> 
                          <script>rellenaGraf('.$datos[A].',"A",'.$datos[B].',"B",'.$datos[C].',"C",'.$datos[D].',"D","'.$key->name.'");</script> 
                        </canvas>
                      </td>
                    </tr>
                  </table> 
              </div>
            </div> 
            <div style="clear: both; margin-top: 10px;"></div>';
          }
          
  $html.='</div>           
        </div>';

  return $html;
}
